### ISSUE TITLE
Error on step2 test "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by mikhail-g** [pact-foundation/pact-workshop-js#158]
Steps:

1. Checkout step2
2. Run tests with `npm test --prefix consumer`

Outcome:
Jest is panicking on `import` at axios

Console output:
```
 FAIL  src/api.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/YOUR_NAME/learn/contract_test/pact-workshop-js/consumer/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import axios from 'axios';
        | ^
      2 |
      3 | export class API {
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/api.js:1:1)
      at Object.<anonymous> (src/api.spec.js:1:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.029 s
```

Workaround:
Exclude axios from `transformIgnorePatterns` to be transformed by Jest. Add the jest config field to `package.json` (or add jest.config file):
```
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(axios)/)"
    ]
  }
```

**Comment by YOU54F** [comment]
Hey thanks @mikhail-g,

It seems I missed that out on step1/2/3.

Your solution is neater than mine

https://github.com/pact-foundation/pact-workshop-js/commit/d52310e702c8130fdd40bd87fb870d3333246dd7

I'll make sure to update and propagate through the steps

**Comment by YOU54F** [comment]
done, thanks!
