### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by loyhaim** [pact-foundation/pact-workshop-js#5]
Hi, 

Thanks for all the work. 

Step 1, I had the following issue in the browser : 

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (C:\Devs\work\pact-workshop-js\consumer\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:317:13)
    at C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\Devs\work\pact-workshop-js\consumer\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:317:13)
    at C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\Devs\work\pact-workshop-js\consumer\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (C:\Devs\work\pact-workshop-js\consumer\node_modules\express\lib\router\layer.js:95:5)`

- Windows 10
- npm 6.12.0
- node 12.13

To fix this, I had to upgrade to react-scripts 3.4.0  (see [this](https://stackoverflow.com/questions/58199001/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re))

**Comment by YOU54F** [comment]
we are now on the latest react scripts (which itself is deprecated) so this _shouldn't_ be an issue now
