### ISSUE TITLE
Alway meet error when run npm run test:pact --prefix consumer

### ISSUE THREAD

**Issue by trangstudio** [pact-foundation/pact-workshop-js#57]
_Thank you for reporting a bug! We appreciate it very much. Issues are a big input into the priorities for Pact-JS development_

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. Mac Catalina 10.15.5
- **Consumer Pact library**: . "@pact-foundation/pact": "^9.11.1",
- **Provider Pact library**: 
- **Node Version**: v14.17.5
- 
### Issue Checklist

Please confirm the following:

- [Confirm ] I have upgraded to the latest
- [Confirm ] I have the read the FAQs in the Readme
- [Confirm ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [Confirm ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ Confirm] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Now I following this tutorial https://docs.pactflow.io/docs/workshops/introduction/readme , at step 3 , I checkout code by 'git checkout step 3', then run command 'npm run test:pact --prefix consumer', so it should 
return 
'❯ npm run test:pact --prefix consumer

PASS src/api.spec.js
PASS src/api.pact.spec.js

Test Suites: 2 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        2.792s, estimated 3s
Ran all test suites.'
### Actual behaviour
'MacBooks-MacBook-Air:pact-workshop-js macbookair$ npm run test:pact --prefix consumer

> consumer@0.1.0 test:pact /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer
> CI=true react-scripts test --testTimeout=30000 pact.spec.js

[2021-09-11T07:14:08.642Z] ERROR: pact-node@10.10.1/39337 on MacBooks-MacBook-Air.local: 
    Pact Binary Error: /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/darwin-1.86.0/pact/lib/ruby/bin/ruby: line 14: project/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/darwin-1.86.0/pact/lib/ruby/lib/ruby/gems/2.2.0: No such file or directory
    
[2021-09-11T07:14:08.646Z]  WARN: pact-node@10.10.1/39337 on MacBooks-MacBook-Air.local: Pact exited with code 1.
FAIL src/api.pact.spec.js (32.635s)
  API Pact test
    getting all products
      ✕ products exists (6ms)
    getting one product
      ✕ ID 10 exists (2ms)

  ● API Pact test › getting all products › products exists

    Pact startup failed; tried calling service 10 times with no result.

      at retry (node_modules/@pact-foundation/pact-node/src/service.ts:219:6)
      at Server.check (node_modules/@pact-foundation/pact-node/src/service.ts:236:5)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)

  ● API Pact test › getting all products › products exists

    TypeError: Cannot read property 'addInteraction' of undefined

      24 | 
      25 |             // set up Pact interactions
    > 26 |             await provider.addInteraction({
         |                            ^
      27 |                 state: 'products exist',
      28 |                 uponReceiving: 'get all products',
      29 |                 withRequest: {

      at Pact.addInteraction (node_modules/@pact-foundation/src/httpPact.ts:102:29)
      at Object.<anonymous> (src/api.pact.spec.js:26:28)

  ● API Pact test › getting all products › products exists

    TypeError: Cannot read property 'verify' of undefined

      17 | 
      18 |     beforeAll(() => provider.setup());
    > 19 |     afterEach(() => provider.verify());
         |                              ^
      20 |     afterAll(() => provider.finalize());
      21 | 
      22 |     describe("getting all products", () => {

      at Pact.verify (node_modules/@pact-foundation/src/httpPact.ts:113:8)
      at Object.<anonymous> (src/api.pact.spec.js:19:30)

  ● API Pact test › getting one product › ID 10 exists

    Pact startup failed; tried calling service 10 times with no result.

      at retry (node_modules/@pact-foundation/pact-node/src/service.ts:219:6)
      at Server.check (node_modules/@pact-foundation/pact-node/src/service.ts:236:5)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:678:19)

  ● API Pact test › getting one product › ID 10 exists

    TypeError: Cannot read property 'addInteraction' of undefined

      59 | 
      60 |             // set up Pact interactions
    > 61 |             await provider.addInteraction({
         |                            ^
      62 |                 state: 'product with ID 10 exists',
      63 |                 uponReceiving: 'get product with ID 10',
      64 |                 withRequest: {

      at Pact.addInteraction (node_modules/@pact-foundation/src/httpPact.ts:102:29)
      at Object.<anonymous> (src/api.pact.spec.js:61:28)

  ● API Pact test › getting one product › ID 10 exists

    TypeError: Cannot read property 'verify' of undefined

      17 | 
      18 |     beforeAll(() => provider.setup());
    > 19 |     afterEach(() => provider.verify());
         |                              ^
      20 |     afterAll(() => provider.finalize());
      21 | 
      22 |     describe("getting all products", () => {

      at Pact.verify (node_modules/@pact-foundation/src/httpPact.ts:113:8)
      at Object.<anonymous> (src/api.pact.spec.js:19:30)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        34.134s
Ran all test suites matching /pact.spec.js/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! consumer@0.1.0 test:pact: `CI=true react-scripts test --testTimeout=30000 pact.spec.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the consumer@0.1.0 test:pact script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbookair/.npm/_logs/2021-09-11T07_14_37_522Z-debug.log'

### Relevant log files

"0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test:pact',
1 verbose cli   '--prefix',
1 verbose cli   'consumer'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'pretest:pact', 'test:pact', 'posttest:pact' ]
5 info lifecycle consumer@0.1.0~pretest:pact: consumer@0.1.0
6 info lifecycle consumer@0.1.0~test:pact: consumer@0.1.0
7 verbose lifecycle consumer@0.1.0~test:pact: unsafe-perm in lifecycle true
8 verbose lifecycle consumer@0.1.0~test:pact: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle consumer@0.1.0~test:pact: CWD: /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer
10 silly lifecycle consumer@0.1.0~test:pact: Args: [ '-c', 'CI=true react-scripts test --testTimeout=30000 pact.spec.js' ]
11 silly lifecycle consumer@0.1.0~test:pact: Returned: code: 1  signal: null
12 info lifecycle consumer@0.1.0~test:pact: Failed to exec test:pact script
13 verbose stack Error: consumer@0.1.0 test:pact: `CI=true react-scripts test --testTimeout=30000 pact.spec.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid consumer@0.1.0
15 verbose cwd /Users/macbookair/Desktop/Automation project/pact-workshop-js
16 verbose Darwin 19.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:pact" "--prefix" "consumer"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error consumer@0.1.0 test:pact: `CI=true react-scripts test --testTimeout=30000 pact.spec.js`
22 error Exit status 1
23 error Failed at the consumer@0.1.0 test:pact script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]"

**Comment by mefellows** [comment]
Moving the issue to the right repository.

Have you first installed the dependencies? Can you please share a clean log of an `npn i`

**Comment by trangstudio** [comment]
Here is the log I capture from CLI: 
'npm i

> pact-workshop-js@0.1.0 postinstall /Users/macbookair/Desktop/Automation project/pact-workshop-js
> concurrently "npm ci --prefix consumer" "npm ci --prefix provider"

[1] npm WARN prepare removing existing node_modules/ before installation
[0] npm WARN prepare removing existing node_modules/ before installation
[1] 
[1] > dtrace-provider@0.8.8 install /Users/macbookair/Desktop/Automation project/pact-workshop-js/provider/node_modules/dtrace-provider
[1] > node-gyp rebuild || node suppress-error.js
[1] 
[1]   ACTION binding_gyp_ndtp_target_build_ndtp .
[1] /bin/sh: project/pact-workshop-js/provider/node_modules/dtrace-provider/build/Release/lib.host:/Users/macbookair/Desktop/Automation: No such file or directory
[0] 
[0] > dtrace-provider@0.8.8 install /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/dtrace-provider
[0] > node-gyp rebuild || node suppress-error.js
[0] 
[0]   ACTION binding_gyp_ndtp_target_build_ndtp .
[0] /bin/sh: project/pact-workshop-js/consumer/node_modules/dtrace-provider/build/Release/lib.host:/Users/macbookair/Desktop/Automation: No such file or directory
[1] -----------------------------------------------------------------
[1] Building dtrace-provider failed with exit code 1, falling back
[1] on stub implementation.
[1] 
[1] Re-run install with V set in your environment to see the build
[1] output, or NODE_DTRACE_PROVIDER_REQUIRE=hard to force an
[1] installation failure.
[1] -----------------------------------------------------------------
[1]   TOUCH Release/obj.target/ndtp.stamp
[1] 
[1] > @pact-foundation/pact-node@10.10.1 postinstall /Users/macbookair/Desktop/Automation project/pact-workshop-js/provider/node_modules/@pact-foundation/pact-node
[1] > node postinstall.js
[1] 
[1] Installing Pact Standalone Binary for darwin.
[1] Downloading Pact Standalone Binary v1.86.0 for platform darwin from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.86.0/pact-1.86.0-osx.tar.gz
[1] Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
[1] Downloaded 0.02%...
[1] Downloaded 1.42%...
[1] Downloaded 3.21%...
[1] Downloaded 5.73%...
[1] Downloaded 8.61%...
[0] -----------------------------------------------------------------
[0] Building dtrace-provider failed with exit code 1, falling back
[0] on stub implementation.
[0] 
[0] Re-run install with V set in your environment to see the build
[0] output, or NODE_DTRACE_PROVIDER_REQUIRE=hard to force an
[0] installation failure.
[0] -----------------------------------------------------------------
[0]   TOUCH Release/obj.target/ndtp.stamp
[0] 
[0] > @pact-foundation/pact-node@10.10.1 postinstall /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node
[0] > node postinstall.js
[0] 
[1] Downloaded 11.45%...
[0] Installing Pact Standalone Binary for darwin.
[0] Downloading Pact Standalone Binary v1.86.0 for platform darwin from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.86.0/pact-1.86.0-osx.tar.gz
[0] Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
[1] Downloaded 14.39%...
[0] Downloaded 0.02%...
[1] Downloaded 16.28%...
[0] Downloaded 1.69%...
[1] Downloaded 17.54%...
[0] Downloaded 3.46%...
[1] Downloaded 18.80%...
[0] Downloaded 4.72%...
[1] Downloaded 20.06%...
[0] Downloaded 6.39%...
[1] Downloaded 21.52%...
[0] Downloaded 8.28%...
[1] Downloaded 22.78%...
[0] Downloaded 10.17%...
[1] Downloaded 23.83%...
[0] Downloaded 11.85%...
[1] Downloaded 24.88%...
[0] Downloaded 13.53%...
[0] Downloaded 14.79%...
[1] Downloaded 25.72%...
[0] Downloaded 16.47%...
[1] Downloaded 26.56%...
[0] Downloaded 17.10%...
[0] Downloaded 19.41%...
[1] Downloaded 27.40%...
[1] Downloaded 28.45%...
[0] Downloaded 21.30%...
[1] Downloaded 29.50%...
[0] Downloaded 22.56%...
[1] Downloaded 30.34%...
[1] Downloaded 30.55%...
[0] Downloaded 23.19%...
[1] Downloaded 31.60%...
[0] Downloaded 23.61%...
[1] Downloaded 33.28%...
[0] Downloaded 24.66%...
[1] Downloaded 35.17%...
[0] Downloaded 25.50%...
[1] Downloaded 36.64%...
[0] Downloaded 26.75%...
[1] Downloaded 37.69%...
[0] Downloaded 28.22%...
[1] Downloaded 38.53%...
[0] Downloaded 29.27%...
[1] Downloaded 39.37%...
[1] Downloaded 41.05%...
[0] Downloaded 30.95%...
[1] Downloaded 42.72%...
[0] Downloaded 32.21%...
[1] Downloaded 44.61%...
[0] Downloaded 33.47%...
[1] Downloaded 46.08%...
[0] Downloaded 34.94%...
[1] Downloaded 49.44%...
[0] Downloaded 36.83%...
[1] Downloaded 51.33%...
[0] Downloaded 38.09%...
[1] Downloaded 53.01%...
[0] Downloaded 39.77%...
[0] Downloaded 41.03%...
[1] Downloaded 54.48%...
[0] Downloaded 42.50%...
[1] Downloaded 56.58%...
[0] Downloaded 45.23%...
[1] Downloaded 57.63%...
[0] Downloaded 45.44%...
[1] Downloaded 58.89%...
[0] Downloaded 47.74%...
[1] Downloaded 60.15%...
[0] Downloaded 48.58%...
[1] Downloaded 61.62%...
[0] Downloaded 50.68%...
[1] Downloaded 64.34%...
[0] Downloaded 53.62%...
[1] Downloaded 66.23%...
[0] Downloaded 54.25%...
[1] Downloaded 68.33%...
[0] Downloaded 55.30%...
[1] Downloaded 70.64%...
[1] Downloaded 70.85%...
[0] Downloaded 56.14%...
[1] Downloaded 73.16%...
[0] Downloaded 57.40%...
[1] Downloaded 74.21%...
[0] Downloaded 58.03%...
[0] Downloaded 59.08%...
[1] Downloaded 76.10%...
[0] Downloaded 60.34%...
[1] Downloaded 77.36%...
[0] Downloaded 62.44%...
[1] Downloaded 79.46%...
[0] Downloaded 63.91%...
[1] Downloaded 80.93%...
[0] Downloaded 64.96%...
[1] Downloaded 82.39%...
[0] Downloaded 66.85%...
[1] Downloaded 83.65%...
[0] Downloaded 68.31%...
[1] Downloaded 84.91%...
[0] Downloaded 69.99%...
[1] Downloaded 86.59%...
[0] Downloaded 71.67%...
[1] Downloaded 88.69%...
[0] Downloaded 72.93%...
[1] Downloaded 90.16%...
[0] Downloaded 73.77%...
[1] Downloaded 91.63%...
[0] Downloaded 74.61%...
[1] Downloaded 94.36%...
[0] Downloaded 75.03%...
[1] Downloaded 95.62%...
[1] Downloaded 97.93%...
[0] Downloaded 75.87%...
[1] Finished downloading binary to /Users/macbookair/Desktop/Automation project/pact-workshop-js/provider/node_modules/@pact-foundation/pact-node/standalone/pact-1.86.0-osx.tar.gz
[1] Extracting binary from /Users/macbookair/Desktop/Automation project/pact-workshop-js/provider/node_modules/@pact-foundation/pact-node/standalone/pact-1.86.0-osx.tar.gz.
[1] Checksum passed for 'pact-1.86.0-osx.tar.gz'.
[0] Downloaded 76.92%...
[1] Extraction done.
[1] 
[1] 
[1] ### If you ❤ Pact and want to support us, please donate here: http://donate.pact.io/node
[1] 
[1] 
[1] Pact Standalone Binary is ready.
[0] Downloaded 81.33%...
[1] 
[1] > fsevents@1.2.9 install /Users/macbookair/Desktop/Automation project/pact-workshop-js/provider/node_modules/fsevents
[1] > node install
[1] 
[0] Downloaded 83.85%...
[1] node-pre-gyp WARN Using request for node-pre-gyp https download 
[0] Downloaded 84.48%...
[0] Downloaded 86.79%...
[1] node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v83-darwin-x64.tar.gz 
[1] node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@14.17.5 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
[0] Downloaded 89.72%...
[0] Downloaded 94.97%...
[0] Finished downloading binary to /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/pact-1.86.0-osx.tar.gz
[0] Extracting binary from /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/pact-1.86.0-osx.tar.gz.
[0] Checksum passed for 'pact-1.86.0-osx.tar.gz'.
[0] Extraction done.
[0] 
[0] 
[0] ### If you ❤ Pact and want to support us, please donate here: http://donate.pact.io/node
[0] 
[0] 
[0] Pact Standalone Binary is ready.
[0] 
[0] > core-js@2.6.11 postinstall /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/babel-runtime/node_modules/core-js
[0] > node -e "try{require('./postinstall')}catch(e){}"
[0] 
[0] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[0] 
[0] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
[0] > https://opencollective.com/core-js 
[0] > https://www.patreon.com/zloirock 
[0] 
[0] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[0] 
[0] 
[0] > fsevents@1.2.11 install /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/chokidar/node_modules/fsevents
[0] > node-gyp rebuild
[0] 
[1]   SOLINK_MODULE(target) Release/.node
[1]   CXX(target) Release/obj.target/fse/fsevents.o
[1] In file included from ../fsevents.cc:6:
[1] In file included from ../../nan/nan.h:2884:
[1] ../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
[1]       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
[1]                                           ^
[1] /Users/macbookair/Library/Caches/node-gyp/14.17.5/include/node/v8.h:5272:3: note: 'GetContents' has been explicitly marked deprecated here
[1]   V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
[1]   ^
[1] /Users/macbookair/Library/Caches/node-gyp/14.17.5/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
[1] # define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
[1]                                       ^
[1] 1 warning generated.
[1]   SOLINK_MODULE(target) Release/fse.node
[1]   COPY /Users/macbookair/Desktop/Automation project/pact-workshop-js/provider/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node
[1]   TOUCH Release/obj.target/action_after_build.stamp
[1] added 709 packages in 163.704s
[1] npm ci --prefix provider exited with code 0
[0]   SOLINK_MODULE(target) Release/.node
[0]   CXX(target) Release/obj.target/fse/fsevents.o
[0] In file included from ../fsevents.cc:6:
[0] In file included from ../../../../nan/nan.h:2884:
[0] ../../../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
[0]       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
[0]                                           ^
[0] /Users/macbookair/Library/Caches/node-gyp/14.17.5/include/node/v8.h:5272:3: note: 'GetContents' has been explicitly marked deprecated here
[0]   V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
[0]   ^
[0] /Users/macbookair/Library/Caches/node-gyp/14.17.5/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
[0] # define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
[0]                                       ^
[0] 1 warning generated.
[0]   SOLINK_MODULE(target) Release/fse.node
[0] 
[0] > core-js@3.6.3 postinstall /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/core-js
[0] > node -e "try{require('./postinstall')}catch(e){}"
[0] 
[0] 
[0] > fsevents@1.2.11 install /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/jest-haste-map/node_modules/fsevents
[0] > node-gyp rebuild
[0] 
[0]   SOLINK_MODULE(target) Release/.node
[0]   CXX(target) Release/obj.target/fse/fsevents.o
[0] In file included from ../fsevents.cc:6:
[0] In file included from ../../../../nan/nan.h:2884:
[0] ../../../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
[0]       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
[0]                                           ^
[0] /Users/macbookair/Library/Caches/node-gyp/14.17.5/include/node/v8.h:5272:3: note: 'GetContents' has been explicitly marked deprecated here
[0]   V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
[0]   ^
[0] /Users/macbookair/Library/Caches/node-gyp/14.17.5/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
[0] # define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
[0]                                       ^
[0] 1 warning generated.
[0]   SOLINK_MODULE(target) Release/fse.node
[0] 
[0] > core-js-pure@3.6.4 postinstall /Users/macbookair/Desktop/Automation project/pact-workshop-js/consumer/node_modules/core-js-pure
[0] > node -e "try{require('./postinstall')}catch(e){}"
[0] 
[0] added 1802 packages in 174.816s
[0] npm ci --prefix consumer exited with code 0
audited 54 packages in 177.025s

2 packages are looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details'

**Comment by mefellows** [comment]
> @mefellows In my opinion , The reason may be that pact-mock_service was not initial

I'm sorry, I'm not sure what you mean by that. Could you please elaborate?

I just did a clean install and it worked OK

```
# clone project
npm ci
git checkout step3
npm run test:pact --prefix consumer

> consumer@0.1.0 test:pact /Users/matthewfellows/development/public/pact-workshop-js/consumer
> CI=true react-scripts test --testTimeout=30000 pact.spec.js

PASS src/api.pact.spec.js (16.608s)
  API Pact test
    getting all products
      ✓ products exists (42ms)
    getting one product
      ✓ ID 10 exists (13ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        17.429s
Ran all test suites matching /pact.spec.js/i.
```

Ran on Node `v12.18.0`.

My guess is it's actually something to do with the space in your project path (see also https://github.com/pact-foundation/pact-js-core/issues/249).

**Comment by trangstudio** [comment]
Hi @mefellows I had did as your suggestion that: 
npm ci
git checkout step3
npm run test:pact --prefix consumer
now it worked for me, BUT when I using: npm i
it always return error when I run this command: npm run test:pact --prefix consumer
As an ref as this link : https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci, with this comparison : 
Essentially, _npm install_ reads **package.json** to create a list of dependencies and uses **package-lock.json** to inform which versions of these dependencies to install. If a dependency is not in **package-lock.json** it will be added by npm install.

_npm ci_ (named after Continuous Integration) installs dependencies directly from **package-lock.json** and uses **package.json** only to validate that there are no mismatched versions. If any dependencies are missing or have incompatible versions, it will throw an error. maybe that having issue with 
I think that having issue with **package.json**

**Comment by mefellows** [comment]
I think the problem is separate. The `npm i` in the root actually calls `npm ci` in the consumer/provider sub-packages.

I think it was more likely a glitch in the matrix, where a package wasn't properly installed.

I just ran this workshop this morning with no problems. I'd suggest removing the various `./node_modules` in the root, consumer and provider folders, and starting again if you're having issues.

**Comment by LaiaPR** [comment]
So, I am having the same issue but in my case I am using:

> OS: Windows 10
> Consumer Pact library: . "@pact-foundation/pact": "^9.11.1"
> Provider Pact library: "@pact-foundation/pact": "^9.11.1"
> Node Version: v14.17.6


And this is what I got when trying to run the Pact test:

`> npm run test:pact --prefix consumer

> consumer@0.1.0 test:pact C:\Users\MYUSER\Workspace\pact-workshop-js\consumer
> react-scripts test --testTimeout=60000 pact.spec.js
[2021-09-15T11:52:34.234Z] ERROR: pact-node@10.10.1/13020 on PF17WGSF:
    Pact Binary Error: C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/request_handlers/interaction_post.rb:1:in `require': cannot load such file -- pact/mock_service/request_handlers/base_administration_request_handler (LoadError)
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/request_handlers/interaction_post.rb:1:in `<top (required)>'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/request_handlers.rb:1:in `require'

[2021-09-15T11:52:34.241Z] ERROR: pact-node@10.10.1/13020 on PF17WGSF:
    Pact Binary Error:  from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/request_handlers.rb:1:in `<top (required)>'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/app.rb:6:in `require'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/app.rb:6:in `<top (required)>'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/run.rb:2:in `require'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/run.rb:2:in `<top (required)>'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/cli.rb:33:in `require'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.6.1/lib/pact/mock_service/cli.rb:33:in `service'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from C:/Users/MYUSER/Workspace/pact-workshop-js/consumer/node_modules/@pact-foundation/pact-node/standalone/win32-1.86.0/pact/lib/app/pact-mock-service.rb:15:in `<main>'

[2021-09-15T11:52:34.278Z]  WARN: pact-node@10.10.1/13020 on PF17WGSF: Pact exited with code 1.`

**Comment by mefellows** [comment]
You're running into the [long path issue](https://github.com/pact-foundation/pact-js-core/issues/100). When we move to the latest v3 version of Pact, this will go away. In the meantime, you need to move the project closer to c:\
