### ISSUE TITLE
Verifier verifyProvider took 17 min to run test

### ISSUE THREAD

**Issue by MikeThuchchai** [pact-foundation/pact-workshop-js#6]
Hi there,

I try to run a test on `src/provider` but it always timeout so I had to setTimeout on Jest and `Verifier(opts)` to 30 sec but it not work so I decided to take 20 min and then it works! It took 17 min to process a test.

Any suggestions on this.
(I'm using node v12.16.1, MacBook air)

## Debug logs here...
<details>
  <summary> Click to expand!</summary>

```
 $ yarn test:pact
yarn run v1.22.4
$ npx jest --testMatch "**/*.pact.test.js"
[2020-05-25T03:27:31.429Z]  INFO: pact@9.11.0/5449 on THUCHCHAIs-MacBook-Air.local: Verifying provider
[2020-05-25T03:27:31.445Z]  INFO: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: Verifying Pacts.
[2020-05-25T03:27:31.446Z]  INFO: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: Verifying Pact Files
[2020-05-25T03:27:31.447Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: Starting pact binary 'standalone/darwin-1.84.0/pact/bin/pact-provider-verifier', with arguments [--provider-states-setup-url http://localhost:51993/_pactSetup --provider-base-url http://localhost:51993 --provider ProductService --provider-app-version 1.0.0 --pact-broker-base-url http://localhost:8081 --broker-username pact_workshop --broker-password pact_workshop], and environment: {"cwd":"/Users/thuchchai/Github/pact-workshop-js/provider/node_modules/@pact-foundation/pact-node","detached":true,"env":{"rvm_use_flag":"","TERM_PROGRAM":"vscode","rvm_bin_path":"/Users/thuchchai/.rvm/bin","NODE":"/usr/local/bin/node","npm_package_devDependencies__pact_foundation_pact":"^9.6.0","INIT_CWD":"/Users/thuchchai/Github/pact-workshop-js/provider","rvm_quiet_flag":"","GEM_HOME":"/Users/thuchchai/.rvm/gems/ruby-2.4.2","ANDROID_HOME":"/Users/thuchchai/Library/Android/sdk","npm_config_version_git_tag":"true","rvm_gemstone_url":"","SHELL":"/bin/zsh","TERM":"xterm-256color","npm_package_devDependencies_jest":"^24.9.0","rvm_docs_type":"","IRBRC":"/Users/thuchchai/.rvm/rubies/ruby-2.4.2/.irbrc","TMPDIR":"/var/folders/qn/5ldvls554cq7rjy0h0fwpr6r0000gp/T/","npm_config_init_license":"MIT","npm_config_email":"thuchchai@thinknet.co.th","TERM_PROGRAM_VERSION":"1.45.1","rvm_hook":"","MY_RUBY_HOME":"/Users/thuchchai/.rvm/rubies/ruby-2.4.2","TERM_SESSION_ID":"***","npm_config_git_tag_version":"","npm_config_registry":"https://registry.yarnpkg.com","LC_ALL":"en_US.UTF-8","ZSH":"/Users/thuchchai/.oh-my-zsh","USER":"thuchchai","npm_package_scripts_test_pact":"npx jest --testMatch \"**/*.pact.test.js\"","npm_package_description":"","npm_config_python":"/usr/bin/python","rvm_gemstone_package_file":"","npm_package_license":"ISC","_system_type":"Darwin","COMMAND_MODE":"unix2003","rvm_path":"/Users/thuchchai/.rvm","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.HR9T4hvDBh/Listeners","__CF_USER_TEXT_ENCODING":"0x1F6:0x0:0x0","npm_package_devDependencies_eslint":"^6.8.0","rvm_proxy":"","npm_execpath":"/usr/local/Cellar/yarn/1.22.4/libexec/bin/yarn.js","rvm_ruby_file":"","PAGER":"less","npm_package_dependencies_cors":"^2.8.5","LSCOLORS":"Gxfxcxdxbxegedabagacad","rvm_silent_flag":"","rvm_prefix":"/Users/thuchchai","rvm_ruby_make":"","PATH":"/Users/thuchchai/Github/pact-workshop-js/provider/node_modules/.bin:/var/folders/qn/5ldvls554cq7rjy0h0fwpr6r0000gp/T/yarn--1590377241825-0.35979851382387706:/Users/thuchchai/Github/pact-workshop-js/provider/node_modules/.bin:/Users/thuchchai/.config/yarn/link/node_modules/.bin:/usr/local/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/bin/node_modules/npm/bin/node-gyp-bin:/Users/thuchchai/.rvm/gems/ruby-2.4.2/bin:/Users/thuchchai/.rvm/gems/ruby-2.4.2@global/bin:/Users/thuchchai/.rvm/rubies/ruby-2.4.2/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin:/Users/thuchchai/ImageMagick-7.0.8/bin:/Users/thuchchai/.fastlane/bin:/Users/thuchchai/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/thuchchai/.rvm/gems/ruby-2.4.2/bin:/Users/thuchchai/.rvm/gems/ruby-2.4.2@global/bin:/Users/thuchchai/.rvm/rubies/ruby-2.4.2/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin:/Users/thuchchai/ImageMagick-7.0.8/bin:/Users/thuchchai/.fastlane/bin:/Users/thuchchai/bin:/Users/thuchchai/Library/Android/sdk/tools:/Users/thuchchai/Library/Android/sdk/tools/bin:/Users/thuchchai/Library/Android/sdk/platform-tools:/Users/thuchchai/.rvm/bin:/Users/thuchchai/Library/Android/sdk/tools:/Users/thuchchai/Library/Android/sdk/tools/bin:/Users/thuchchai/Library/Android/sdk/platform-tools:/Users/thuchchai/.rvm/bin","npm_config_argv":"{\"remain\":[],\"cooked\":[\"run\",\"test:pact\"],\"original\":[\"test:pact\"]}","_":"/usr/local/bin/npx","LaunchInstanceID":"5D1006F6-8044-460F-B7E6-D42D15C92426","PWD":"/Users/thuchchai/Github/pact-workshop-js/provider","JAVA_HOME":"/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home","npm_lifecycle_event":"test:pact","rvm_sdk":"","LANG":"en_US.UTF-8","npm_package_name":"product-service","ITERM_PROFILE":"Default","npm_package_scripts_start":"node server.js","npm_config_version_commit_hooks":"true","_system_arch":"x86_64","XPC_FLAGS":"0x0","npm_config_username":"thuchchai","npm_config_bin_links":"true","_system_version":"10.15","MAGICK_HOME":"/Users/thuchchai/ImageMagick-7.0.8","npm_package_main":"app.js","XPC_SERVICE_NAME":"0","npm_package_version":"1.0.0","rvm_version":"1.29.7 (latest)","rvm_script_name":"","rvm_pretty_print_flag":"","COLORFGBG":"15;0","SHLVL":"4","HOME":"/Users/thuchchai","rvm_ruby_mode":"","VSCODE_GIT_ASKPASS_MAIN":"/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","npm_package_scripts_test":"npx jest","LC_TERMINAL_VERSION":"3.3.7","npm_config_save_prefix":"^","npm_config_strict_ssl":"true","npm_config_version_git_message":"v%s","NPM_CONFIG_PYTHON":"/usr/bin/python","ITERM_SESSION_ID":"****","LOGNAME":"thuchchai","LESS":"-R","YARN_WRAP_OUTPUT":"false","PREFIX":"/usr/local","rvm_alias_expanded":"","npm_lifecycle_script":"npx jest --testMatch \"**/*.pact.test.js\"","LC_CTYPE":"en_US.UTF-8","VSCODE_GIT_IPC_HANDLE":"/var/folders/qn/5ldvls554cq7rjy0h0fwpr6r0000gp/T/vscode-git-3548be83de.sock","GEM_PATH":"/Users/thuchchai/.rvm/gems/ruby-2.4.2:/Users/thuchchai/.rvm/gems/ruby-2.4.2@global","rvm_nightly_flag":"","npm_config_version_git_sign":"","npm_config_ignore_scripts":"","npm_config_user_agent":"yarn/1.22.4 npm/? node/v12.16.1 darwin x64","rvm_ruby_make_install":"","VSCODE_GIT_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","GIT_ASKPASS":"/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh","rvm_niceness":"","LC_TERMINAL":"iTerm2","rvm_ruby_bits":"","npm_package_dependencies_express":"^4.17.1","rvm_bin_flag":"","npm_config_init_version":"1.0.0","npm_config_ignore_optional":"","rvm_only_path_flag":"","SECURITYSESSIONID":"186a6","RUBY_VERSION":"ruby-2.4.2","_system_name":"OSX","COLORTERM":"truecolor","npm_node_execpath":"/usr/local/bin/node","npm_config_version_tag_prefix":"v","NODE_ENV":"test","JEST_WORKER_ID":"1"}}
[2020-05-25T03:27:31.457Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: Created 'standalone/darwin-1.84.0/pact/bin/pact-provider-verifier' process with PID: 5469
[2020-05-25T03:32:35.094Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
    INFO: Fetching pacts for ProductService from http://localhost:8081
    INFO: Reading pact at http://pact_workshop:*****@localhost:8081/pacts/provider/ProductService/consumer/FrontendWebsite/version/86a4112
    
    
[2020-05-25T03:32:35.097Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
    Verifying a pact between FrontendWebsite and ProductService
      Given products exist
        get all products
          with GET /products
            returns a response which
    

 RUNS  product/product.pact.test.js
[2020-05-25T03:35:05.646Z] DEBUG: pact@9.11.0/5449 on THUCHCHAIs-MacBook-Air.local: Proxing /products
[2020-05-25T03:35:05.681Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has status code 200
              has a matching body
              includes headers
                "Content-Type" which equals "application/json; charset=utf-8"
      Given no products exist
        get all products
          with GET /products
            returns a response which
    
[2020-05-25T03:37:36.678Z] DEBUG: pact@9.11.0/5449 on THUCHCHAIs-MacBook-Air.local: Proxing /products
[2020-05-25T03:37:36.717Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has status code 200
    
[2020-05-25T03:37:36.719Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has a matching body
    
[2020-05-25T03:37:36.720Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              includes headers
    
[2020-05-25T03:37:36.721Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
                "Content-Type" which equals "application/json; charset=utf-8"
      Given products exist
    
[2020-05-25T03:37:36.726Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
        get all products with no auth token
    
[2020-05-25T03:37:36.726Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
          with GET /products
    
[2020-05-25T03:37:36.726Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
            returns a response which
    
[2020-05-25T03:40:07.511Z] DEBUG: pact@9.11.0/5449 on THUCHCHAIs-MacBook-Air.local: Proxing /products
[2020-05-25T03:40:07.532Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has status code 401
    
[2020-05-25T03:40:07.537Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
      Given product with ID 10 exists
    
[2020-05-25T03:40:07.537Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
        get product with ID 10
          with GET /product/10
    
[2020-05-25T03:40:07.537Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
            returns a response which
    
[2020-05-25T03:42:38.557Z] DEBUG: pact@9.11.0/5449 on THUCHCHAIs-MacBook-Air.local: Proxing /product/10
[2020-05-25T03:42:38.596Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has status code 200
    
[2020-05-25T03:42:38.602Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has a matching body
    
[2020-05-25T03:42:38.602Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              includes headers
    
[2020-05-25T03:42:38.610Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
                "Content-Type" which equals "application/json; charset=utf-8"
    
[2020-05-25T03:42:38.611Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
      Given product with ID 11 does not exist
    
[2020-05-25T03:42:38.611Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
        get product with ID 11
    
[2020-05-25T03:42:38.612Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
          with GET /product/11
    
[2020-05-25T03:42:38.612Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
            returns a response which
    
[2020-05-25T03:45:09.544Z] DEBUG: pact@9.11.0/5449 on THUCHCHAIs-MacBook-Air.local: Proxing /product/11
[2020-05-25T03:45:09.578Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has status code 404
    
[2020-05-25T03:45:09.579Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
      Given product with ID 10 exists
    
[2020-05-25T03:45:09.579Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
        get product by ID 10 with no auth token
          with GET /product/10
            returns a response which
    
[2020-05-25T03:45:09.589Z] DEBUG: pact@9.11.0/5449 on THUCHCHAIs-MacBook-Air.local: Proxing /product/10
[2020-05-25T03:45:09.595Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
              has status code 401
    
[2020-05-25T03:45:09.598Z] DEBUG: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: 
    
    6 interactions, 0 failures
```

</details>

## Last Result 

```
 PASS  product/product.pact.test.js (1062.351s)
  Pact Verification
    ✓ validates the expectations of ProductService (1058327ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1064.617s
Ran all test suites.
[2020-05-25T03:45:09.682Z]  INFO: pact-node@10.9.4/5449 on THUCHCHAIs-MacBook-Air.local: Pact Verification succeeded.
  console.log product/product.pact.test.js:66
    Pact Verification Complete!

  console.log product/product.pact.test.js:67
    INFO: Fetching pacts for ProductService from http://localhost:8081
    INFO: Reading pact at http://pact_workshop:*****@localhost:8081/pacts/provider/ProductService/consumer/FrontendWebsite/version/86a4112
    
    
    Verifying a pact between FrontendWebsite and ProductService
      Given products exist
        get all products
          with GET /products
            returns a response which
    
              has status code 200
              has a matching body
              includes headers
                "Content-Type" which equals "application/json; charset=utf-8"
      Given no products exist
        get all products
          with GET /products
            returns a response which
    
              has status code 200
    
              has a matching body
    
              includes headers
    
                "Content-Type" which equals "application/json; charset=utf-8"
      Given products exist
    
        get all products with no auth token
    
          with GET /products
    
            returns a response which
    
              has status code 401
    
      Given product with ID 10 exists
    
        get product with ID 10
          with GET /product/10
    
            returns a response which
    
              has status code 200
    
              has a matching body
    
              includes headers
    
                "Content-Type" which equals "application/json; charset=utf-8"
    
      Given product with ID 11 does not exist
    
        get product with ID 11
    
          with GET /product/11
    
            returns a response which
    
              has status code 404
    
      Given product with ID 10 exists
    
        get product by ID 10 with no auth token
          with GET /product/10
            returns a response which
    
              has status code 401
    
    6 interactions, 0 failures
    
✨  Done in 1068.36s.
```

**Comment by praveen-em** [comment]
Sorry to ask a question on an issue which was closed 3 years ago. Just curious as to whether you managed to solve this issue @MikeThuchchai ? I am facing the same issue but it's while running in our corporate CI server. It takes about 17 mins to complete. I tried using pact in V3 format (assuming that is what @mefellows was suggesting) but didn't make any difference. 

With shorter timeout, I see the following open handles. Removed the timeout and saw it finish successfully after around 17 mins. 

```
22:28:36  Jest has detected the following 2 open handles potentially keeping Jest from exiting:
22:28:36  
22:28:36    ���  TCPSERVERWRAP
22:28:36  
22:28:36      [0m [90m  9 |[39m app[33m.[39muse(authMiddleware)[33m;[39m
22:28:36       [90m 10 |[39m app[33m.[39muse(require([32m'./product.routes'[39m))[33m;[39m
22:28:36      [31m[1m>[22m[39m[90m 11 |[39m [36mconst[39m server [33m=[39m app[33m.[39mlisten([32m"8080"[39m)[33m;[39m
22:28:36       [90m    |[39m                    [31m[1m^[22m[39m
22:28:36       [90m 12 |[39m
22:28:36       [90m 13 |[39m describe([32m"Pact Verification"[39m[33m,[39m () [33m=>[39m {
22:28:36       [90m 14 |[39m     it([32m"validates the expectations of ProductService"[39m[33m,[39m [36masync[39m () [33m=>[39m {[0m
22:28:36  
22:28:36        at Function.listen (node_modules/express/lib/application.js:635:24)
22:28:36        at Object.listen (product/product.pact.test.js:11:20)
22:28:36  
22:28:36  
22:28:36    ���  TCPSERVERWRAP
22:28:36  
22:28:36      [0m [90m 76 |[39m         }
22:28:36       [90m 77 |[39m
22:28:36      [31m[1m>[22m[39m[90m 78 |[39m         [36mreturn[39m [36mnew[39m [33mVerifier[39m(opts)[33m.[39mverifyProvider()[33m.[39mthen(output [33m=>[39m {
22:28:36       [90m    |[39m                                   [31m[1m^[22m[39m
22:28:36       [90m 79 |[39m             console[33m.[39mlog(output)[33m;[39m
22:28:36       [90m 80 |[39m         })[33m.[39m[36mfinally[39m(() [33m=>[39m {
22:28:36       [90m 81 |[39m             server[33m.[39mclose()[33m;[39m[0m
22:28:36  
22:28:36        at createProxy (node_modules/@pact-foundation/src/dsl/verifier/proxy/proxy.ts:89:6)
22:28:36        at Verifier.Object.<anonymous>.Verifier.verifyProvider (node_modules/@pact-foundation/src/dsl/verifier/verifier.ts:92:31)
22:28:36        at Object.verifyProvider (product/product.pact.test.js:78:35)

```

**Comment by mefellows** [comment]
It might be worth bumping the Pact JS version to the latest to see if that fixes it - could you please try that locally @praveen-em and if that works, we could get the whole project up to date?

**Comment by praveen-em** [comment]
@mefellows , I was actually using latest version `12.5.2`. I just found the culprit. It was that tracking thing enabled by default. Setting `PACT_DO_NOT_TRACK=true` did the trick.

**Comment by mefellows** [comment]
aha! That's interesting, it should be a non-blocking call. I wonder if it's DNS resolution or something blocking it (or are you saying that's the open handle being detected)?

**Comment by praveen-em** [comment]
My guess is that the firewall blocking the outbound connection (which is expected in corporate environment) and it's probably retrying before it gives up in about 17 mins. I could see the verification results in the broker immediately but they get logged only after 17 mins, so I guess whatever tracker was trying to do wasn't blocking verification and publish activities. Yea, when I kept the jest timeout to shorter duration, it showed two open handles.
