### ISSUE TITLE
Pact broker docker compose fail to start

### ISSUE THREAD

**Issue by edouard-lopez** [pact-foundation/pact-workshop-js#65]
Using 92a5b937a1d1a0c16093296861250bfb59f2b178, I wasn't able to start a broker after `git checkout step11`

```
❯ docker compose up
[+] Running 3/3
 ⠿ Network pact-workshop-js_default         Created                                                                                                                                                           0.0s
 ⠿ Container pact-workshop-js-postgres-1    Created                                                                                                                                                           0.0s
 ⠿ Container pact-workshop-js-broker_app-1  Created                                                                                                                                                           0.0s
Attaching to pact-workshop-js-broker_app-1, pact-workshop-js-postgres-1
pact-workshop-js-postgres-1    | The files belonging to this database system will be owned by user "postgres".
pact-workshop-js-postgres-1    | This user must also own the server process.
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | The database cluster will be initialized with locale "en_US.utf8".
pact-workshop-js-postgres-1    | The default database encoding has accordingly been set to "UTF8".
pact-workshop-js-postgres-1    | The default text search configuration will be set to "english".
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | Data page checksums are disabled.
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
pact-workshop-js-postgres-1    | creating subdirectories ... ok
pact-workshop-js-postgres-1    | selecting dynamic shared memory implementation ... posix
pact-workshop-js-postgres-1    | selecting default max_connections ... 100
pact-workshop-js-postgres-1    | selecting default shared_buffers ... 128MB
pact-workshop-js-postgres-1    | selecting default time zone ... Etc/UTC
pact-workshop-js-postgres-1    | creating configuration files ... ok
pact-workshop-js-postgres-1    | running bootstrap script ... ok
pact-workshop-js-broker_app-1  | Puma starting in single mode...
pact-workshop-js-broker_app-1  | * Puma version: 5.5.2 (ruby 2.6.8-p205) ("Zawgyi")
pact-workshop-js-broker_app-1  | *  Min threads: 0
pact-workshop-js-broker_app-1  | *  Max threads: 5
pact-workshop-js-broker_app-1  | *  Environment: production
pact-workshop-js-broker_app-1  | *          PID: 8
pact-workshop-js-postgres-1    | performing post-bootstrap initialization ... ok
pact-workshop-js-postgres-1    | syncing data to disk ... ok
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | Success. You can now start the database server using:
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | initdb: warning: enabling "trust" authentication for local connections
pact-workshop-js-postgres-1    | You can change this by editing pg_hba.conf or using the option -A, or
pact-workshop-js-postgres-1    | --auth-local and --auth-host, the next time you run initdb.
pact-workshop-js-postgres-1    | waiting for server to start....2021-12-02 21:20:54.230 UTC [47] LOG:  starting PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.231 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.234 UTC [48] LOG:  database system was shut down at 2021-12-02 21:20:54 UTC
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.237 UTC [47] LOG:  database system is ready to accept connections
pact-workshop-js-postgres-1    |  done
pact-workshop-js-postgres-1    | server started
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.355 UTC [47] LOG:  received fast shutdown request
pact-workshop-js-postgres-1    | waiting for server to shut down....2021-12-02 21:20:54.356 UTC [47] LOG:  aborting any active transactions
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.357 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.357 UTC [49] LOG:  shutting down
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.365 UTC [47] LOG:  database system is shut down
pact-workshop-js-broker_app-1  | 2021-12-02 21:20:54.340654 I [8:70132409424380] pact-broker -- Connecting to database: -- "{:adapter=>\"postgres\", :user=>\"postgres\", :password=>\"*****\", :host=>\"postgres\", :database=>\"postgres\", :encoding=>\"utf8\", :sql_log_level=>:debug, :enable_caller_logging=>false, :log_warn_duration=>5.0, :pool_timeout=>5, :driver_options=>{:options=>\"-c statement_timeout=15s\"}, :connect_max_retries=>0}"
pact-workshop-js-broker_app-1  | ! Unable to load application: Sequel::DatabaseConnectionError: PG::ConnectionBad: could not connect to server: Connection refused
pact-workshop-js-broker_app-1  | 	Is the server running on host "postgres" (172.22.0.2) and accepting
pact-workshop-js-broker_app-1  | 	TCP/IP connections on port 5432?
pact-workshop-js-broker_app-1  | bundler: failed to load command: puma (/pact_broker/vendor/bundle/ruby/2.6.0/bin/puma)
pact-workshop-js-postgres-1    |  done
pact-workshop-js-postgres-1    | server stopped
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | PostgreSQL init process complete; ready for start up.
pact-workshop-js-postgres-1    | 
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.498 UTC [1] LOG:  starting PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.498 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.498 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.500 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.503 UTC [66] LOG:  database system was shut down at 2021-12-02 21:20:54 UTC
pact-workshop-js-postgres-1    | 2021-12-02 21:20:54.507 UTC [1] LOG:  database system is ready to accept connections
pact-workshop-js-broker_app-1  | /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:210:in `initialize': PG::ConnectionBad: could not connect to server: Connection refused (Sequel::DatabaseConnectionError)
pact-workshop-js-broker_app-1  | 	Is the server running on host "postgres" (172.22.0.2) and accepting
pact-workshop-js-broker_app-1  | 	TCP/IP connections on port 5432?
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:210:in `new'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:210:in `connect'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool.rb:122:in `make_new'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:278:in `test_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/misc.rb:175:in `initialize'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:57:in `new'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:57:in `connect'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/core.rb:124:in `connect'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/initializers/database_connection.rb:17:in `block in create_database_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/initializers/database_connection.rb:31:in `with_retries'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/initializers/database_connection.rb:16:in `create_database_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/app.rb:135:in `configure_database_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/app.rb:99:in `post_configure'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/app.rb:50:in `initialize'
pact-workshop-js-broker_app-1  | 	from config.ru:4:in `new'
pact-workshop-js-broker_app-1  | 	from config.ru:4:in `block in <main>'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/configuration.rb:345:in `load_rackup'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/configuration.rb:267:in `app'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/runner.rb:149:in `load_and_bind'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/single.rb:44:in `run'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/launcher.rb:181:in `run'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/cli.rb:80:in `run'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/bin/puma:10:in `<top (required)>'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli/exec.rb:63:in `load'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli/exec.rb:63:in `kernel_load'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli/exec.rb:28:in `run'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli.rb:494:in `exec'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli.rb:30:in `dispatch'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli.rb:24:in `start'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/exe/bundle:49:in `block in <top (required)>'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/exe/bundle:37:in `<top (required)>'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/bin/bundle:23:in `load'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/bin/bundle:23:in `<main>'
pact-workshop-js-broker_app-1  | /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:210:in `initialize': could not connect to server: Connection refused (PG::ConnectionBad)
pact-workshop-js-broker_app-1  | 	Is the server running on host "postgres" (172.22.0.2) and accepting
pact-workshop-js-broker_app-1  | 	TCP/IP connections on port 5432?
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:210:in `new'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:210:in `connect'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool.rb:122:in `make_new'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:278:in `test_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/misc.rb:175:in `initialize'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:57:in `new'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:57:in `connect'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.50.0/lib/sequel/core.rb:124:in `connect'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/initializers/database_connection.rb:17:in `block in create_database_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/initializers/database_connection.rb:31:in `with_retries'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/initializers/database_connection.rb:16:in `create_database_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/app.rb:135:in `configure_database_connection'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/app.rb:99:in `post_configure'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.92.0/lib/pact_broker/app.rb:50:in `initialize'
pact-workshop-js-broker_app-1  | 	from config.ru:4:in `new'
pact-workshop-js-broker_app-1  | 	from config.ru:4:in `block in <main>'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/configuration.rb:345:in `load_rackup'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/configuration.rb:267:in `app'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/runner.rb:149:in `load_and_bind'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/single.rb:44:in `run'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/launcher.rb:181:in `run'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/lib/puma/cli.rb:80:in `run'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-5.5.2/bin/puma:10:in `<top (required)>'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
pact-workshop-js-broker_app-1  | 	from /pact_broker/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli/exec.rb:63:in `load'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli/exec.rb:63:in `kernel_load'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli/exec.rb:28:in `run'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli.rb:494:in `exec'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli.rb:30:in `dispatch'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/cli.rb:24:in `start'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/exe/bundle:49:in `block in <top (required)>'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/gems/bundler-2.2.10/exe/bundle:37:in `<top (required)>'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/bin/bundle:23:in `load'
pact-workshop-js-broker_app-1  | 	from /usr/local/bundle/bin/bundle:23:in `<main>'
pact-workshop-js-broker_app-1 exited with code 1
```

**Comment by edouard-lopez** [comment]
Solution was to edit `./docker-compose.yaml`:

```diff
-    image: pactfoundation/pact-broker
+    image: pactfoundation/pact-broker:2
```

and run again:

    ❯ docker compose up

**Comment by bethesque** [comment]
Try setting `PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "10"` in the environment variables of the pact broker service. Because postgres takes longer to start up than the puma process, the database isn't ready to accept connections when puma tries to connect.

**Comment by YOU54F** [comment]
updated now across the steps with the pact-broker as well as restart "always"

thanks for raising as always @edouard-lopez
