### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by ZebraFlesh** [pact-foundation/pact-workshop-js#9]
Using node 12.18.2 and the bundled version of npm, executing `npm install` on Windows 10 results in the following output:

```bash
[0] > fsevents@1.2.11 install C:\Users\nope\git\pact-workshop-js\consumer\node_modules\chokidar\node_modules\fsevents
[0] > node-gyp rebuild
[0]
[0]
[0] C:\Users\nope\git\pact-workshop-js\consumer\node_modules\chokidar\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
[0] Traceback (most recent call last):
[0]   File "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
[0]     sys.exit(gyp.script_main())
[0]   File "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
[0]     return main(sys.argv[1:])
[0]   File "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
[0]     return gyp_main(args)
[0]   File "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
[0]     generator.GenerateOutput(flat_list, targets, data, params)
[0]   File "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2030, in GenerateOutput
[0]     sln_projects, project_objects, flat=msvs_version.FlatSolution())
[0]   File "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1787, in _GatherSolutionFolders
[0]     return _DictsToFolders('', root, flat)
[0]   File "C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1740, in _DictsToFolders
[0]     for folder, contents in bucket.items():
[0] AttributeError: 'MSVSProject' object has no attribute 'items'
[0] gyp ERR! configure error
[0] gyp ERR! stack Error: `gyp` failed with exit code: 1
[0] gyp ERR! stack     at ChildProcess.onCpExit (C:\ProgramData\nvm\v12.18.2\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
[0] gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
[0] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[0] gyp ERR! System Windows_NT 10.0.19041
[0] gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\nvm\\v12.18.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0] gyp ERR! cwd C:\Users\nope\git\pact-workshop-js\consumer\node_modules\chokidar\node_modules\fsevents
[0] gyp ERR! node -v v12.18.2
[0] gyp ERR! node-gyp -v v5.1.0
[0] gyp ERR! not ok
```

What the heck is going on here? Why is fsevents even attempting to build on Windows?

**Comment by omulriain** [comment]
I am having this same issue. 

try to run npm test --prefix consumer and get 
'CI' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.


in my npm install history I see the following.
AttributeError: 'MSVSProject' object has no attribute 'items'
[0] gyp ERR! configure error
[0] gyp ERR! stack Error: `gyp` failed with exit code: 1
[0] gyp ERR! stack     at ChildProcess.onCpExit (D:\Program Files\nodejs\node_modul
es\npm\node_modules\node-gyp\lib\configure.js:351:16)
[0] gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
[0] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proce
ss.js:275:12)
[0] gyp ERR! System Windows_NT 10.0.18362
[0] gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\node
js\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[0] gyp ERR! cwd D:\projects\pact-workshop-js\consumer\node_modules\jest-haste-map\
node_modules\fsevents
[0] gyp ERR! node -v v12.18.3
[0] gyp ERR! node-gyp -v v5.1.0
[0] gyp ERR! not ok
[0]
[0] > core-js-pure@3.6.4 postinstall D:\projects\pact-workshop-js\consumer\node_mod
ules\core-js-pure
[0] > node -e "try{require('./postinstall')}catch(e){}"
[0]
[0] added 1686 packages in 110.169s
[0] npm ci --prefix consumer exited with code 0
audited 65 packages in 111.888s

**Comment by mefellows** [comment]
Not sure why it's failing, but it's a dependency for react:

```
npm list fsevents
consumer@0.1.0 /Users/matthewfellows/development/public/pact-workshop-js/consumer
└─┬ react-scripts@3.3.0
  ├─┬ babel-jest@24.9.0
  │ └─┬ @jest/transform@24.9.0
  │   └─┬ jest-haste-map@24.9.0
  │     └── fsevents@1.2.11
  ├── fsevents@2.1.2
  └─┬ webpack-dev-server@3.9.0
    └─┬ chokidar@2.1.8
      └── fsevents@1.2.11
```

This looks to be a React issue to me.

**Comment by Joost-SF** [comment]
same issue for me as well

**Comment by mefellows** [comment]
Which one? There are multiple in this thread. 

I believe the `CI` environment variable will be fixed by #67 which would need merging into all branches.

I'll leave this open to track it, but PRs welcome.

**Comment by YOU54F** [comment]
cross-env has now been applied across all the steps, I still need to give it a whirl on a windows box. I'll report back shortly

**Comment by YOU54F** [comment]
cross-env is added to all steps, windows installation errors have been resolved by using prebuilt ffi node bundles in the npm package
